[project]
name = "cudf-rs"
channels = ["rapidsai", "nvidia", "conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[system-requirements]
cuda = "13"

[dependencies]
cuda-crt = "13.*"
cuda-cudart-dev = "13.*"
cxx-compiler = "*"
libcudf = "25.10.00.*"
libcurl = "*"
rust = "*"
