[project]
name = "cudf-rs"
channels = ["rapidsai", "nvidia", "conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[system-requirements]
cuda = "13"

[dependencies]
cuda-version = "13.*"
cuda-cccl = "*"
cuda-crt = "*"
cuda-cudart-dev = "*"
cxx-compiler = "*"
libcudf = "25.10.00.*"
libcurl = "*"
rust = "*"
